console.log ("*Cocinar Una Torta*")
console.log ("1. Batir 2 huevos")
console.log ("2. Añadir 150g de azucar")
console.log ("3. Incorporar 150ml de leche")
console.log ("4. Agregar esencia de vainilla")
console.log ("5. Batir hasta que se integren")
console.log ("6. Agregar 150g harina leudante")
console.log ("7. Remover ingredientes")
console.log ("8. Engrasar un molde con aceite")
console.log ("9. Vaciar mezcla en el molde")
console.log ("10. Cocinar en horno a 180 grados")
console.log ("11. Sacar torta al transcurrir 50mn")
console.log ("12. Esperar a que enfrie")
console.log ("13. Quitar torta del molde")
console.log ("14. Cortar la torta en varias porciónes")
console.log ("15. Servir y disfrutar la porción")
